services:
 
  auth-service:
    build: 
      context: ./AuthService
      dockerfile: Dockerfile
    ports:
      - "9090:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres-auth;Port=5432;Database=auth;Username=postgres;Password=postgres123
      - Jwt__SecretKey=YourSecretKeyHere123456789012345678901234567890
      - Jwt__Issuer=AuthService
      - Jwt__Audience=CallCenterAPI
    depends_on:
      - postgres-auth

  postgres-auth:
    image: postgres:15
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

volumes:
  postgres_auth_data:
